apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq01
spec:
  selector:
    matchLabels:
      app: vprormq01
  template:
    metadata:
      labels:
        app: vprormq01
    spec:
      containers:
        - name: vprormq01
          image: rabbitmq
          ports:
            - name: rabbitmq-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:  
                secretKeyRef:
                    name: mysecret
                    key: rmqpass

            - name: RABBITMQ_DEFAULT_USER
              value: guest
            
        
          
